### ISSUE TITLE
Error while parsing cli flags

### ISSUE THREAD

**Issue by danhorvath** [chromaui/chromatic-cli#235]
Hey!

Since today all our chromatic builds have been failing with the following error:

```

$ npx chromatic --project-token XXX
npx: installed 321 in 8.41s
Unhandled promise rejection: Flag keys may not contain '-': project-token, app-code, build-script-name, output-dir, storybook-build-dir, allow-console-errors, auto-accept-changes, exit-once-uploaded, exit-zero-on-changes, ignore-last-build-on-branch, patch-build, preserve-missing, junit-report, do-not-start, script-name, storybook-port, storybook-url, storybook-https, storybook-cert, storybook-key, storybook-ca
```

Based on the stack trace this issue is probably related to a new release in the `meow` dependency https://github.com/sindresorhus/meow/releases/tag/v8.1.1

**Comment by MichaelPeter** [comment]
One of my colleagues had the same Problem, but now I tried it on my pc (npm chromatic 5.50) and it worked.

Could this have been a server issue? Is it still occuring for others?

**Comment by Greg-mso** [comment]
@MichaelPeter Working for me now too, thanks for the heads up

**Comment by MichaelPeter** [comment]
Edit: For me the error is happen now again:

Unhandled promise rejection: Flag keys may not contain '-': project-token, app-code, build-script-name, output-dir, storybook-build-dir, allow-console-errors, auto-accept-changes, exit-once-uploaded, exit-zero-on-changes, ignore-last-build-on-branch, patch-build, preserve-missing, junit-report, do-not-start, script-name, storybook-port, storybook-url, storybook-https, storybook-cert, storybook-key, storybook-ca
Error: Flag keys may not contain '-': project-token, app-code, build-script-name, output-dir, storybook-build-dir, allow-console-errors, auto-accept-changes, exit-once-uploaded, exit-zero-on-changes, ignore-last-build-on-branch, patch-build, preserve-missing, junit-report, do-not-start, script-name, storybook-port, storybook-url, storybook-https, storybook-cert, storybook-key, storybook-ca
    at validateOptions (XXX\node_modules\chromatic\node_modules\meow\index.js:61:9)
    at meow (XXX\node_modules\chromatic\node_modules\meow\index.js:136:2)
    at parseArgs (XXX\node_modules\chromatic\bin\lib\parseArgs.js:4:39)

**Comment by MichaelPeter** [comment]
As seen here, meow.js released a version 8.1.2 without the change made a major version 9 with the breaking change https://github.com/sindresorhus/meow/issues/173.

So deleting the 8.1.1 package in chromatic and reinstalling 8.1.2 fixes the problem.


thank you mr @sindresorhus

**Comment by danhorvath** [comment]
Thanks for updating us @MichaelPeter! Couldn't find the 8.1.2 release on https://github.com/sindresorhus/meow/releases but I see that it's there on [npm](https://www.npmjs.com/package/meow). With that the issue is resolved, I'm closing the ticket.

**Comment by bodograumann** [comment]
Can we please reopen this?
The problem is back, because of the recent dependency update that included meow 9

**Comment by danhorvath** [comment]
@bodograumann we don't experience this issue so I suggest that you open a new ticket - maybe it's related to your specific setup.

**Comment by bodograumann** [comment]
The problem was reintroduced in 5.6.2, maybe you have not updated yet. Otherwise I'd be happy to create a new ticket.

**Comment by TheSonOfThomp** [comment]
Just upgraded to 5.6.2, and still seeing this issue

**Comment by danhorvath** [comment]
Guys please open a new ticket with this. We don't experience this problem and so I'd rather not manage this ticket since I won't be able to provide further info to the maintainers.

**Comment by danhorvath** [comment]
It seems one was already opened https://github.com/chromaui/chromatic-cli/issues/281

**Comment by bodograumann** [comment]
Sorry, I did not intent to bother you with this.
I feel it is usually a good thing to keep all information for a specific issue in one place.
That way people can find it more easily.

Of course if this causes problems for you, I will respect your decision.

**Comment by tmeasday** [comment]
@bodograumann / @TheSonOfThomp are you seeing the issue: "Flag keys may not contain '-': " or the "The flag --projectToken can only be set once" issue?

**Comment by TheSonOfThomp** [comment]
@tmeasday Im seeing the "Flag keys may not contain '-': " issue on 5.6.2
