### ISSUE TITLE
chromaui/action github action gives deprecation warnings about set-output

### ISSUE THREAD

**Issue by davedash** [chromaui/chromatic-cli#672]
If I use the chromaui/action I get warnings from Github Actions:

> storybook
> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

I am no expert in developing Github Actions, but hopefully this is helpful:

From looking at `@actions/core` and this codebase, it seems like `setOutput` effectively produces deprecated code.  An alternative can be found [here][1] to set an environment variable.  This env variable can be used similarly to how the output values are used.

[1]: https://github.com/actions/toolkit/blob/dd046652c32b45c0207b37ee0bc0ebf43a28b257/docs/commands.md#set-an-environment-variable

**Comment by levity** [comment]
Looks like this was fixed in #666, and we're just waiting for a new release

**Comment by ethriel3695** [comment]
@levity @davedash 
It looks like we did release the change https://github.com/chromaui/action/tree/v1
v6.11.4

The Changelog did not update to reflect the release, however.
We will work on updating the Changelog.

The node update is available with v6.11.4

**Comment by hendricksond** [comment]
I'm using chromaui/action@v1, v6.11.4, and still getting these warnings. Maybe there's another dependency that needs to be updated? Unfortunately, the action logs don't give any useful info - just 13 instances of the `set-output` deprecation warning:

```
Build 208 completed
    → Tested 16 stories across 15 components; captured 16 snapshots in 11 seconds

Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

... etc
```

**Comment by ethriel3695** [comment]
@hendricksond 
I opened up an internal ticket to get this resolved.
We will update you as soon as we have a solution.

**Comment by ghengeveld** [comment]
Should be resolved now. Let me know if not.

**Comment by levity** [comment]
The latest version on https://github.com/marketplace/actions/publish-to-chromatic is still v1; is this expected?

**Comment by ghengeveld** [comment]
Yes, this is expected. We have no versioning on the GitHub Action, it is always the latest version. We intend to change that in the future, but it's not as trivial as it sounds unfortunately (we'd want to do semver, but that means publishing multiple tags with each release).
